name: task_alarm_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  fl_chart: ^0.69.0
  alarm: ^5.0.0
  camera: ^0.11.0
  google_mlkit_pose_detection: ^0.13.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  ios: true
  android: true
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/alarm_sound.mp3
    - assets/sounds/mikhail-krug-letnijj-den.mp3